spring.application.name=Mottu Mapping API
spring.profiles.active=${SPRING_PROFILES_ACTIVE}
#spring.config.import=classpath:env.properties

# jpa / hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#cache
spring.cache.type=simple

# pool size
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.validation-timeout=5000

# security
spring.security.basic.enabled=false

# thymeleaf
spring.thymeleaf.cache=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
